# Sample config for 1 experiment
model:
  layers:
    - name: flatten

    - name: linear
      in_shape: 784
      out_shape: 128

    - name: dropout
      prob: 0.5

    - name: leaky_relu
      slope: 0.01

    - name: linear
      in_shape: 128
      out_shape: 64

    - name: dropout
      prob: 0.5

    - name: elu
      alpha: 0.8

    - name: linear
      in_shape: 64
      out_shape: 10

    - name: relu

train:
  lr: 0.01
  batch_size: 64
  num_epochs: 2
  loss: cross_entropy
  optim: adam

data:
  dir: ../data
  transforms:
    - name: to_tensor